//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "library")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub name: String,
    pub category: String,
    pub language: String,
    pub region: String,
    pub metadata_provider: Option<String>,
    pub scanned_at: Option<DateTimeUtc>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::library_directory::Entity")]
    LibraryDirectory,
}

impl Related<super::library_directory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LibraryDirectory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
