[package]
name = "corgi"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
corgi-core = { workspace = true }
corgi-server = { workspace = true }

clap = { version = "4.5.23", features = ["derive"] }
tokio = { workspace = true }
dotenvy = "0.15.7"
