[package]
name = "corgi-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
corgi-database = { workspace = true }
corgi-types = { workspace = true }

serde = { workspace = true }
thiserror = { workspace = true }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
toml = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
argon2 = { workspace = true }
tokio = { workspace = true }
jsonwebtoken = { workspace = true }
rand_core = { workspace = true }
ed25519-dalek = { workspace = true }
http = { workspace = true }
