[package]
name = "corgi-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
corgi-database = { path = "../corgi-database" }

tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
tracing = "0.1.41"
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"
utoipa = { version = "5.3.1", features = ["uuid", "chrono"] }
uuid = { version = "1.11.0", features = ["v7"] }
chrono = "0.4.39"
argon2 = "0.5.3"
thiserror = "2.0.9"
tokio = "1.42.0"
jsonwebtoken = "9.3.0"
rand = "0.8.5"
ed25519-dalek = { version = "2.1.1", features = ["pkcs8", "rand_core"] }
