[package]
name = "corgi-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
corgi-database = { path = "../corgi-database" }

tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = "0.1.40"
serde = { version = "1.0.211", features = ["derive"] }
toml = "0.8.19"
utoipa = { version = "5.1.1", features = ["uuid", "chrono"] }
uuid = { version = "1.11.0", features = ["v7"] }
chrono = "0.4.38"
argon2 = "0.5.3"
thiserror = "2.0.3"
tokio = "1.41.1"
