[package]
name = "corgi-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
corgi-core = { path = "../corgi-core" }

axum = "0.8.1"
axum-extra = { version = "0.10.0", features = ["typed-header"] }
tokio = { workspace = true }
tower-http = { version = "0.6.2", features = ["trace"] }
utoipa = { workspace = true }
utoipa-axum = "0.2.0"
utoipa-swagger-ui = { version = "9.0.0", features = ["axum"] }
serde = { workspace = true }
thiserror = { workspace = true }
garde = { version = "0.22.0", features = ["full"] }
sysinfo = "0.33.1"
